# -*- mode:org; fill-column:79; -*-

#+TITLE:Introduction to Web Development
#+AUTHOR:WLHarvey4

#+MACRO: EDITION 0.1
#+MACRO: VERSION 0.0.5

#+TEXINFO: @insertcopying

* Course Info
** About this Course
   This course is designed to start you  on a path toward future studies in web
   development  and  design,  no  matter how  little  experience  or  technical
   knowledge you currently have.   The web is a very big place,  and if you are
   the typical  internet user, you  probably visit several websites  every day,
   whether  for  business,  entertainment  or education.   But  have  you  ever
   wondered how  these websites  actually work?   How are  they built?   How do
   browsers, computers, and mobile devices  interact with the web?  What skills
   are necessary to build a website?  With almost 1 billion websites now on the
   internet, the answers  to these questions could be your  first step toward a
   better understanding  of the internet and  developing a new set  of internet
   skills.

   By the  end of  this course  you’ll be  able to  describe the  structure and
   functionality  of the  world  wide web,  create dynamic  web  pages using  a
   combination  of  HTML,  CSS,  and JavaScript,  apply  essential  programming
   language  concepts  when creating  HTML  forms,  select an  appropriate  web
   hosting service, and  publish your webpages for the world  to see.  Finally,
   you’ll be able to develop a working  model for creating your own personal or
   business websites in the future and be  fully prepared to take the next step
   in a more advanced web development or design course or specialization.

   - Level :: Beginner
   - Commitment :: 6 weeks of study,  2-3 hours/week; approximately 16 hours to
                   complete
   - Skills :: CSS; HTML; JavaScript;

** About the Instructor
   -  Daniel Randall,  Senior Architect  at Composer Solutions  and Instructor,
     @@texinfo:@abbr{@@U.C. Davis@@texinfo:}@@

   Dan  Randall has  over  25  years’ experience  in  software engineering  and
   information  technology  and currently  works  in  the software  development
   industry focusing  on software  modernization.  He is  the co-author  of the
   {{{cite(Java Web  Services Certification  Exam for Sun  Microsystems)}}} and
   the associated training and practice materials for test takers.  The exam is
   taken by  thousands of  programmers worldwide.  Dan  was also  the technical
   editor for the book {{{cite(Think Like  a Programmer)}}}.  He earned a BS in
   computer  science  from American  Sentinel  University  where he  was  named
   Outstanding  Graduate and  the recipient  of the  Joe @@texinfo:@abbr{B@.}@@
   Wyatt Leadership  Award.  He later earned  an MS in computer  science and is
   currently a  @@texinfo:@abbr{Ph.D}@@ candidate  in computer science  at Nova
   Southeastern University.  He teaches computer science and web development at
   several  universities, including  the UC@@texinfo:@tie{}@@Davis  Division of
   Continuing and Professional Education.  His research interests are currently
   artificial intelligence, programming languages and machine learning.

** Course Overview
   Welcome to the  fundamentals of web development. I commend  you for choosing
   to learn something about the  foundations of web development. Whether you're
   planning on being a  web developer part-time, or just as a  hobby, or even a
   full-time  developer, I  think this  course can  help you  get started.

   My name's  Dan Randall.   I'm a  software developer  and a  computer science
   professor. In  this course we're  going to start  with the basics,  and with
   your attention and practice and a lot of persistence you'll be able to learn
   to create your own websites.  Some of  the things we'll learn in this course
   are  common abbreviations  and terms  used in  web development  and software
   development in  general.  You'll be able  to find and select  your web host,
   register  your  site,   and  discuss  and  work   with  various  client-side
   development techniques, and learn a little bit about server-side development
   and  how  it   works  with  general  web  application   development  on  the
   internet.

   Some of the technologies we'll use  are HTML, CSS, JavaScript, and more. And
   we'll learn more  about those as we  move through the course.  One of things
   you'll learn  is creating a dynamic  HTML site that uses  JavaScript so that
   you'll be able to accept your user's interaction, their input, and make your
   site respond to  their needs.  Learning the fundamentals  of web development
   will help you as you move on to future courses and learn to build larger and
   more complex  sites. Everyone can  use the skills  we teach in  this course.
   Today as we  use the internet more and more,  including mobile phones, these
   skills can benefit everyone,  whether you're treating it as a  hobby or as a
   profession. Thanks for  joining me, I look forward to  working with you, and
   I'll see you in future lessons in the course.

** Syllabus

*** Week 1---Course Overview and Website Structure and Hosting
:PROPERTIES:
:hours:    4
:END:

This  first  module  provides  an  overview of  how  websites  function,  their
structure, and  the ins and  outs of choosing a  website name and  selecting an
online host to house  your website.  By the end of this  module, you'll be able
to:

- find and select a web hosting company;
- choose an effective domain name;
- use the host to manage your websites; and
- discuss how networks and the internet function at a high level.

**** Week 1 Videos
- Course Overview 1m
- Module 1 Introduction 54s
- What is a Web Hosting Company? 4m
- How to Find and Select a Web Hosting Company 4m
- Naming a Website 2m
- Website Name Registration 4m
- Networks and the Internet 3m
- First Look at a Website Control Panel 4m
- Web Development Tools 6m

**** Week 1 Readings
- Web Hosting Additional Resources 45m
- Suggested Activity: Website Hosting and Naming 1h 30m

**** Week 1 Practice Exercise
- Module 1 Quiz 20m

*** Week 2---Designing Your Own Website: HTML Basics
:PROPERTIES:
:hours:    5
:END:

In this  module, we'll begin  to explore how to  design and create  websites by
exploring the  base language used  to power all websites:  HTML.  By the  end of
this lesson, you'll be able to:
- identify and use common HTML tags;
- add an image to a webpage;
- create HTML-formatted tables;
- use hyperlinks to connect a series of webpages;
- upload your finished HTML pages to a web host; and,
- learn some tips and tricks for styling pages and practicing your coding.

**** Week 2 Videos
- Module 2 Introduction1m
- Components and Structure of a Website2m
- Creating Your Own HTML: Setting Up a Template6m
- Creating Your Own HTML: Creating Links and Formatting Text9m
- Creating Your Own HTML: Working with Images8m
- Creating Your Own HTML: Working with Tables7m
- Creating HTML - How to Practice7m
- How to Put Your HTML on the Internet3m
- How to Test Your HTML5m
- Basic Styling in Webpages6m

**** Week 2 Reading
- HTML Additional Resources45m

**** Week 2 Practice Exercise
- Module 2 Quiz 20m

*** Week 3---Introduction to Programming Using JavaScript
:PROPERTIES:
:hours:    3
:END:

Now that you know some basic HTML, it's time to turn our attention to another
common scripting language used to make websites dynamic - that is allowing
users to interact with your webpages - JavaScript.  While learning about
JavaScript, you'll also gain some foundational knowledge common to all
programming languages.  By the end of this module, you'll be able to: discuss
what is meant by
- dynamic content;
- perform essential programming language tasks;
- create simple JavaScript programs;
- use JavaScript to set up alerts and respond to events,
- to read input, and
- to change HTML; and
- conduct basic JavaScript testing.

**** Week 3 Videos
- Module 3 Introduction 1m
- Static vs. Dynamic Webpages 5m
- The Value of JavaScript to Our Websites 3m
- JavaScript Basics: Fundamental Syntax, Part 15m
- JavaScript Basics: Fundamental Syntax, Part 210m
- Putting JavaScript to Work: Using Alerts and Prompts 9m
- Putting Javascript to Work: Events 7m
- Putting JavaScript to Work: Gathering Additional User Input and Dynamically
  Modifying HTML 6m
- Testing JavaScript 8m

**** Week 3 Reading
- JavaScript Additional Resources 45m

**** Week 3 Practice Exericse
- Module 3 Quiz 20m

*** Week 4---Websites with Style--CSS Properties, Colors and Fonts
:PROPERTIES:
:hours:    4
:END:

While  HTML and  JavaScript are  very useful  for web  development, they  don't
exactly make websites look attractive - that's where cascading style sheets, or
CSS, comes into play.   While HTML is used to build the  structure of our pages
and JavaScript  is used to  provide interactive  functionality, CSS is  used to
graphically design and  layout webpages.  By the end of  this module, you'll be
able to:
- discuss common mistakes in designing a website;
- identify and apply CSS basics like  purpose and syntax;
- use  CSS properties to control  fonts, colors, layouts, and other common
  properties;
- differentiate between in-line, internal, and external CSS; and
- practice and test your cascading style sheets.

**** Week 4 Videos
- Module 4 Introduction 2m
- Plain Websites are Boring 4m
- CSS Basics, Part 16m
- CSS Basics, Part 24m
- Putting CSS to Work: Getting Started with External CSS 7m
- Putting CSS to Work: Setting Colors with CSS 4m
- Putting CSS to Work: Controlling Your Page Layout 4m
- Putting CSS to Work: Common CSS Properties 4m
- How to Practice CSS 4m
- Testing Website Styles 6m

**** Week 4 Readings
- CSS Additional Resources 45m

**** Week 4 Practice Exercise
- Module 4 Quiz 20m

*** Week 5---Creating HTML Forms
:PROPERTIES:
:hours:    4
:END:

In this lesson, we're going to learn  to apply all of the skills we've acquired
so far to make  a very common, and very useful type of  webpage - an HTML form.
HTML  forms  are seen  everywhere  on  the internet  and  are  used to  capture
particular information  from users in  a variety of ways.   By the end  of this
module you'll be able to:
- create basic HTML forms;
- identify and appropriately use different types of HTML input;
- validate user input;
- submit HTML forms; and
- test how your forms are working and troubleshoot errors.

**** Week 5 Videos
- Module 5 Introduction 1m
- HTML Forms User Input 7m
- HTML Form Elements 7m
- HTML Form Validation: JavaScript 6m
- HTML Form Validation: Complex Form Example 5m
- HTML Form Validation: Additional Features 7m
- HTML Form Validation: Processing 5m

**** Week 5 Reading
- HTML Forms Additional Resources 45m

**** Week 5 Practice Exercise
Module 5 Quiz 20m

*** Week 6---Creating Web Applications
:PROPERTIES:
:hours:    5
:END:

In our final module, we're going to explore the basics of designing web
applications - programming useful and dynamic webpages that allow our users to
interact with them. By the end of this lesson you'll be able to:
- distinguish between client and server-side development;
- apply advanced JavaScript programming skills to create logic with selection
  and iteration; create new features for applications;
- create more advanced HTML forms; and
- practice and learn additional troubleshooting and problem-solving techniques.


**** Week 6 Videos
- Module 6 Introduction 1m
- Client-side versus Server-side Application Development 4m
- Features in Web Applications: The While Loop 5m
- Features in Web Applications: The For Loop 5m
- Creating New Features in Web Applications 3m
- Guided Practice with HTML Form Validation, Part 1 5m
- Guided Practice with HTML Form Validation, Part 2 7m
- Course Summary 1m


The module wraps with a final peer review activity that will draw upon all of
the skills you've learned in this course.

**** Week 6 Readings
- Validating HTML Forms 45m

**** Week 6 Exercise
- Module 6 Quiz 20m

* Website Structure • Website Hosting
  #+cindex:hosting, website
  #+cindex:structure, website
  #+cindex:module one

  - Objectives for Module One: Website Structure • Hosting
    + define what a website hosting company does
    + why you need a website hosting company
    + how to select a hosting company
    + how to identify a good name for your site
    + how to reserve a name at a low price
    + explain how the domain name serve works
    + know some common tools used in web development

** Introduction to Website Structure and Hosting
   Hi,  and  welcome   to  the  first  module  in  the   Fundamentals  of  Web
   Development. In this first module we're going to focus on some foundational
   details we really need to know before we get into the details of coding. By
   the end of this  module you should be able to do a  few things. Among them,
   define what a  website hosting company does  and why you need  them. How to
   select a hosting company and how to  identify a good name for your site and
   reserve it at  a low price. You'll  also be able to explain  how the domain
   name service works. And  learn about some of the common  tools we use every
   day in  web development. Obviously,  this is a lot  to cover, so  let's get
   started talking about web hosting.

** Web Hosting
   #+cindex:web hosting
   #+cindex:hosting, web
   #+cindex:hosting services
   Hi  and welcome  to the  lesson.  Today,  I'd like  to discuss  Web Hosting.

   {{{dfn(Web  Hosting)}}}   is  *a   service  that   allows  people   to  post
   websites*.

   #+cindex:servers
   #+cindex:networking equipment
   @@texinfo:@noindent@@  Of  course,  people   and  businesses  too.   Hosting
   services provide  special equipment.  Support for  that equipment, including
   24  hours support  and technology  most people  don't have  available.  This
   includes {{{dfn(servers)}}},  which are *really expensive  high availability
   computers*.  Networking  equipment and dedicated network  access.

   {{{heading(Hosting Types)}}}
   #+cindex:hosts, types
   #+cindex:free hosting
   #+cindex:hosting, free
   #+cindex:shared hosting
   #+cindex:hosting, shared
   #+cindex:dedicated hosting
   #+cindex:hosting, dedicated
   - Free
   - Shared
   - Dedicated


   There are  different types of  host.  Some  of them provide  *free hosting*.
   Free hosting  can be convenient,  particularly when we're starting  out, but
   the problem with free hosting is usually the service provided are of limited
   quality.  So when we're  choosing a host, if we choose a  free host, we have
   to understand  that we're probably going  to get what we  paid for.  *Shared
   hosting*, by  far, the most common.   Shared hosting is low  cost.  Meaning,
   it's not  particularly expensive.   In the  US, it would  probably be  a few
   dollars a  month, but  the cost  is kept down,  because the  hosting service
   shares resources  between different websites.  And  then finally, *dedicated
   hosting* and  this is  higher cost, but  it allows us  to have  a dedicated,
   personalize service within a hosting  center.  This is usually not necessary
   and is reserved for large businesses who  need this kind of service.  So for
   us, we are usually  working with free or more often  shared low cost hosting
   services.

   {{{heading(Website Hosting Services)}}}
   #+cindex:services, hosting
   #+cindex:hosting services
   #+cindex:FTP
   #+cindex:File Transfer Protocol
   - Disk Space
   - Email
   - FTP
   - Management Software
   - Reliable Internet
   - With Economy


   So, let's talk a little bit about what kind of services are provided.  So, a
   hosting service provides us *disk space for files*. Now as we learn later on
   the course,  our websites  are composed  of many  files.  This  include HTML
   files and images,  both of which we'll discuss later  in the course.  *Email
   accounts*.   So  for most  hosting  services,  they  will provide  us  Email
   Accounts. For  instance, if we  have a service or  rather a business  with a
   particular name  say, "Joe's Boat Service",  we can get Email  Accounts that
   will include the name "Joe's Boat Service" or any name that we chose for our
   website. We get *File transfer software*, which is usually called FTP, which
   stands for {{{dfn(File Transfer Protocol)}}}  and this allows us to transfer
   files from our computers where we're working  on a website up to the hosting
   service, where the  files can be displayed as part  of our website.  Hosting
   services give us *Management Software*,  which allows us to manipulate files
   on our  site and do other  work on our site,  such as starting the  site and
   stopping the site and making any modifications  we want to do and that we do
   this  through the  Management  Software, the  hosting  service provides  us.
   Hosting services give us *Reliable Internet*.   Now many of us have Internet
   at home or perhaps  we access internet on our phones,  on our smartphones or
   possibly at a library or university.   Well, hosting services have their own
   internet, usually  they have  several sources of  internet and  they provide
   this to us when we're using them as a hosting service to keep our website up
   and available to anybody  who might want to see it.   And finally, a hosting
   service gives us all  of these things with *economy*.  Now,  a few dollars a
   month for a shared site is relatively inexpensive in most cases.  If we were
   to buy this equipment  or to have a dedicated site  to house this equipment,
   it would  typically cost  thousands of  dollars to  accomplish.  So  the few
   dollars a month or  sometimes even cheaper, if we pay for  a year in advance
   is definitely a bargain. So, I will talk to you next time.

* HTML Basics

* JavaScript

* CSS • Properties • Colors • Fonts

* HTML Forms

* Web Applications

* Copying
  :PROPERTIES:
  :COPYING:  t
  :END:

This manual is for {{{title}}} Edition {{{EDITION}}}@@texinfo:@*@@
Version {{{VERSION}}} {{{time(%F %R)}}}

Copyright \copy 2018 {{{author}}}

#+BEGIN_QUOTE
Permission is granted to read, learn from, and enjoy this work.
#+END_QUOTE

* Concept Index
  :PROPERTIES:
  :INDEX:    cp
  :END:

* Settings :noexport:
#+OPTIONS: H:4 ':t *:t

#+TEXINFO_CLASS: info

#+TEXINFO_FILENAME:intro_web_dev.info
#+TEXINFO_PRINTED_TITLE:Intro to Web Development
#+SUBTITLE:From UC Davis --- Edition {{{EDITION}}}@@texinfo:@*@@Version {{{VERSION}}} {{{time(%F %R)}}}

#+TEXINFO_HEADER:
#+TEXINFO_POST_HEADER:

#+TEXINFO_DIR_CATEGORY:Web Development
#+TEXINFO_DIR_TITLE:Introduction to WebDev
#+TEXINFO_DIR_DESC:Introduction to web development from UC Davis

** Macros
#+MACRO: cite @@texinfo:@cite{@@$1@@texinfo:}@@
#+MACRO: var @@texinfo:@var{@@$1@@texinfo:}@@
#+MACRO: kbd (eval (let ((case-fold-search nil) (regexp (regexp-opt '("SPC" "RET" "LFD" "TAB" "BS" "ESC" "DELETE" "SHIFT" "Ctrl" "Meta" "Alt" "Cmd" "Super" "UP" "LEFT" "RIGHT" "DOWN") 'words))) (format "@@texinfo:@kbd{@@%s@@texinfo:}@@" (replace-regexp-in-string regexp "@@texinfo:@key{@@\\&@@texinfo:}@@" $1 t))))
#+MACRO: dfn @@texinfo:@dfn{@@$1@@texinfo:}@@
#+MACRO: heading @@texinfo:@heading @@$1
#+MACRO: subheading @@texinfo:@subheading @@$1
