# -*- mode:org; fill-column:79; -*-

#+TITLE:Introduction to Web Development
#+AUTHOR:WLHarvey4

#+MACRO: EDITION 0.1
#+MACRO: VERSION 0.0.4

#+TEXINFO: @insertcopying

* Course Info


** About this Course
   This course is designed to start you  on a path toward future studies in web
   development  and  design,  no  matter how  little  experience  or  technical
   knowledge you currently have.   The web is a very big place,  and if you are
   the typical  internet user, you  probably visit several websites  every day,
   whether  for  business,  entertainment  or education.   But  have  you  ever
   wondered how  these websites  actually work?   How are  they built?   How do
   browsers, computers, and mobile devices  interact with the web?  What skills
   are necessary to build a website?  With almost 1 billion websites now on the
   internet, the answers  to these questions could be your  first step toward a
   better understanding  of the internet and  developing a new set  of internet
   skills.

   By the  end of  this course  you’ll be  able to  describe the  structure and
   functionality  of the  world  wide web,  create dynamic  web  pages using  a
   combination  of  HTML,  CSS,  and JavaScript,  apply  essential  programming
   language  concepts  when creating  HTML  forms,  select an  appropriate  web
   hosting service, and  publish your webpages for the world  to see.  Finally,
   you’ll be able to develop a working  model for creating your own personal or
   business websites in the future and be  fully prepared to take the next step
   in a more advanced web development or design course or specialization.

   - Level :: Beginner
   - Commitment :: 6 weeks of study, 2-3 hours/week

** About the Instructor
   -  Daniel Randall,  Senior Architect  at Composer Solutions  and Instructor,
     @@texinfo:@abbr{@@U.C. Davis@@texinfo:}@@

   Dan  Randall has  over  25  years’ experience  in  software engineering  and
   information  technology  and currently  works  in  the software  development
   industry focusing  on software  modernization.  He is  the co-author  of the
   {{{cite(Java Web  Services Certification  Exam for Sun  Microsystems)}}} and
   the associated training and practice materials for test takers.  The exam is
   taken by  thousands of  programmers worldwide.  Dan  was also  the technical
   editor for the book {{{cite(Think Like  a Programmer)}}}.  He earned a BS in
   computer  science  from American  Sentinel  University  where he  was  named
   Outstanding  Graduate and  the recipient  of the  Joe @@texinfo:@abbr{B@.}@@
   Wyatt Leadership  Award.  He later earned  an MS in computer  science and is
   currently a  @@texinfo:@abbr{Ph.D}@@ candidate  in computer science  at Nova
   Southeastern University.  He teaches computer science and web development at
   several  universities, including  the UC@@texinfo:@tie{}@@Davis  Division of
   Continuing and Professional Education.  His research interests are currently
   artificial intelligence, programming languages and machine learning.

** Course Overview
   Welcome to the  fundamentals of web development. I commend  you for choosing
   to learn something about the  foundations of web development. Whether you're
   planning on being a  web developer part-time, or just as a  hobby, or even a
   full-time  developer, I  think this  course can  help you  get started.

   My name's  Dan Randall.   I'm a  software developer  and a  computer science
   professor. In  this course we're  going to start  with the basics,  and with
   your attention and practice and a lot of persistence you'll be able to learn
   to create your own websites.  Some of  the things we'll learn in this course
   are  common abbreviations  and terms  used in  web development  and software
   development in  general.  You'll be able  to find and select  your web host,
   register  your  site,   and  discuss  and  work   with  various  client-side
   development techniques, and learn a little bit about server-side development
   and  how  it   works  with  general  web  application   development  on  the
   internet.

   Some of the technologies we'll use  are HTML, CSS, JavaScript, and more. And
   we'll learn more  about those as we  move through the course.  One of things
   you'll learn  is creating a dynamic  HTML site that uses  JavaScript so that
   you'll be able to accept your user's interaction, their input, and make your
   site respond to  their needs.  Learning the fundamentals  of web development
   will help you as you move on to future courses and learn to build larger and
   more complex  sites. Everyone can  use the skills  we teach in  this course.
   Today as we  use the internet more and more,  including mobile phones, these
   skills can benefit everyone,  whether you're treating it as a  hobby or as a
   profession. Thanks for  joining me, I look forward to  working with you, and
   I'll see you in future lessons in the course.

* Website Structure • Website Hosting
  #+cindex:hosting, website
  #+cindex:structure, website
  #+cindex:module one

  - Objectives for Module One: Website Structure • Hosting
    + define what a website hosting company does
    + why you need a website hosting company
    + how to select a hosting company
    + how to identify a good name for your site
    + how to reserve a name at a low price
    + explain how the domain name serve works
    + know some common tools used in web development

** Introduction to Website Structure and Hosting
   Hi,  and  welcome   to  the  first  module  in  the   Fundamentals  of  Web
   Development. In this first module we're going to focus on some foundational
   details we really need to know before we get into the details of coding. By
   the end of this  module you should be able to do a  few things. Among them,
   define what a  website hosting company does  and why you need  them. How to
   select a hosting company and how to  identify a good name for your site and
   reserve it at  a low price. You'll  also be able to explain  how the domain
   name service works. And  learn about some of the common  tools we use every
   day in  web development. Obviously,  this is a lot  to cover, so  let's get
   started talking about web hosting.

** Web Hosting
   #+cindex:web hosting
   #+cindex:hosting, web
   #+cindex:hosting services
   Hi  and welcome  to the  lesson.  Today,  I'd like  to discuss  Web Hosting.

   {{{dfn(Web  Hosting)}}}   is  *a   service  that   allows  people   to  post
   websites*.

   #+cindex:servers
   #+cindex:networking equipment
   @@texinfo:@noindent@@  Of  course,  people   and  businesses  too.   Hosting
   services provide  special equipment.  Support for  that equipment, including
   24  hours support  and technology  most people  don't have  available.  This
   includes {{{dfn(servers)}}},  which are *really expensive  high availability
   computers*.  Networking  equipment and dedicated network  access.

   {{{heading(Hosting Types)}}}
   #+cindex:hosts, types
   #+cindex:free hosting
   #+cindex:hosting, free
   #+cindex:shared hosting
   #+cindex:hosting, shared
   #+cindex:dedicated hosting
   #+cindex:hosting, dedicated
   - Free
   - Shared
   - Dedicated


   There are  different types of  host.  Some  of them provide  *free hosting*.
   Free hosting  can be convenient,  particularly when we're starting  out, but
   the problem with free hosting is usually the service provided are of limited
   quality.  So when we're  choosing a host, if we choose a  free host, we have
   to understand  that we're probably going  to get what we  paid for.  *Shared
   hosting*, by  far, the most common.   Shared hosting is low  cost.  Meaning,
   it's not  particularly expensive.   In the  US, it would  probably be  a few
   dollars a  month, but  the cost  is kept down,  because the  hosting service
   shares resources  between different websites.  And  then finally, *dedicated
   hosting* and  this is  higher cost, but  it allows us  to have  a dedicated,
   personalize service within a hosting  center.  This is usually not necessary
   and is reserved for large businesses who  need this kind of service.  So for
   us, we are usually  working with free or more often  shared low cost hosting
   services.

   {{{heading(Website Hosting Services)}}}
   #+cindex:services, hosting
   #+cindex:hosting services
   #+cindex:FTP
   #+cindex:File Transfer Protocol
   - Disk Space
   - Email
   - FTP
   - Management Software
   - Reliable Internet
   - With Economy


   So, let's talk a little bit about what kind of services are provided.  So, a
   hosting service provides us *disk space for files*. Now as we learn later on
   the course,  our websites  are composed  of many  files.  This  include HTML
   files and images,  both of which we'll discuss later  in the course.  *Email
   accounts*.   So  for most  hosting  services,  they  will provide  us  Email
   Accounts. For  instance, if we  have a service or  rather a business  with a
   particular name  say, "Joe's Boat Service",  we can get Email  Accounts that
   will include the name "Joe's Boat Service" or any name that we chose for our
   website. We get *File transfer software*, which is usually called FTP, which
   stands for {{{dfn(File Transfer Protocol)}}}  and this allows us to transfer
   files from our computers where we're working  on a website up to the hosting
   service, where the  files can be displayed as part  of our website.  Hosting
   services give us *Management Software*,  which allows us to manipulate files
   on our  site and do other  work on our site,  such as starting the  site and
   stopping the site and making any modifications  we want to do and that we do
   this  through the  Management  Software, the  hosting  service provides  us.
   Hosting services give us *Reliable Internet*.   Now many of us have Internet
   at home or perhaps  we access internet on our phones,  on our smartphones or
   possibly at a library or university.   Well, hosting services have their own
   internet, usually  they have  several sources of  internet and  they provide
   this to us when we're using them as a hosting service to keep our website up
   and available to anybody  who might want to see it.   And finally, a hosting
   service gives us all  of these things with *economy*.  Now,  a few dollars a
   month for a shared site is relatively inexpensive in most cases.  If we were
   to buy this equipment  or to have a dedicated site  to house this equipment,
   it would  typically cost  thousands of  dollars to  accomplish.  So  the few
   dollars a month or  sometimes even cheaper, if we pay for  a year in advance
   is definitely a bargain. So, I will talk to you next time.

* HTML Basics

* JavaScript

* CSS • Properties • Colors • Fonts

* HTML Forms

* Web Applications

* Copying
  :PROPERTIES:
  :COPYING:  t
  :END:

This manual is for {{{title}}} Edition {{{EDITION}}}@@texinfo:@*@@
Version {{{VERSION}}} {{{time(%F %R)}}}

Copyright \copy 2018 {{{author}}}

#+BEGIN_QUOTE
Permission is granted to read, learn from, and enjoy this work.
#+END_QUOTE

* Concept Index
  :PROPERTIES:
  :INDEX:    cp
  :END:

* Settings :noexport:
#+OPTIONS: H:4 ':t *:t

#+TEXINFO_CLASS: info

#+TEXINFO_FILENAME:intro_web_dev.info
#+TEXINFO_PRINTED_TITLE:Intro to Web Development
#+SUBTITLE:From UC Davis --- Edition {{{EDITION}}}@@texinfo:@*@@Version {{{VERSION}}} {{{time(%F %R)}}}

#+TEXINFO_HEADER:
#+TEXINFO_POST_HEADER:

#+TEXINFO_DIR_CATEGORY:Web Development
#+TEXINFO_DIR_TITLE:Introduction to WebDev
#+TEXINFO_DIR_DESC:Introduction to web development from UC Davis

** Macros
#+MACRO: cite @@texinfo:@cite{@@$1@@texinfo:}@@
#+MACRO: var @@texinfo:@var{@@$1@@texinfo:}@@
#+MACRO: kbd (eval (let ((case-fold-search nil) (regexp (regexp-opt '("SPC" "RET" "LFD" "TAB" "BS" "ESC" "DELETE" "SHIFT" "Ctrl" "Meta" "Alt" "Cmd" "Super" "UP" "LEFT" "RIGHT" "DOWN") 'words))) (format "@@texinfo:@kbd{@@%s@@texinfo:}@@" (replace-regexp-in-string regexp "@@texinfo:@key{@@\\&@@texinfo:}@@" $1 t))))
#+MACRO: dfn @@texinfo:@dfn{@@$1@@texinfo:}@@
#+MACRO: heading @@texinfo:@heading @@$1
#+MACRO: subheading @@texinfo:@subheading @@$1
