# -*- mode:org; fill-column:79; -*-

#+TITLE:Introduction to Web Development
#+AUTHOR:WLHarvey4

#+MACRO: EDITION 0.1
#+MACRO: VERSION 0.0.2

#+TEXINFO: @insertcopying

* Course Info

** About this Course
   This course is designed to start you  on a path toward future studies in web
   development  and  design,  no  matter how  little  experience  or  technical
   knowledge you currently have.   The web is a very big place,  and if you are
   the typical  internet user, you  probably visit several websites  every day,
   whether  for  business,  entertainment  or education.   But  have  you  ever
   wondered how  these websites  actually work?   How are  they built?   How do
   browsers, computers, and mobile devices  interact with the web?  What skills
   are necessary to build a website?  With almost 1 billion websites now on the
   internet, the answers  to these questions could be your  first step toward a
   better understanding  of the internet and  developing a new set  of internet
   skills.

   By the  end of  this course  you’ll be  able to  describe the  structure and
   functionality  of the  world  wide web,  create dynamic  web  pages using  a
   combination  of  HTML,  CSS,  and JavaScript,  apply  essential  programming
   language  concepts  when creating  HTML  forms,  select an  appropriate  web
   hosting service, and  publish your webpages for the world  to see.  Finally,
   you’ll be able to develop a working  model for creating your own personal or
   business websites in the future and be  fully prepared to take the next step
   in a more advanced web development or design course or specialization.

   - Level :: Beginner
   - Commitment :: 6 weeks of study, 2-3 hours/week

** About the Instructor
   -  Daniel Randall,  Senior Architect  at Composer Solutions  and Instructor,
     @@texinfo:@abbr{@@U.C. Davis@@texinfo:}@@

   Dan  Randall has  over  25  years’ experience  in  software engineering  and
   information  technology  and currently  works  in  the software  development
   industry focusing  on software  modernization.  He is  the co-author  of the
   {{{cite(Java Web  Services Certification  Exam for Sun  Microsystems)}}} and
   the associated training and practice materials for test takers.  The exam is
   taken by  thousands of  programmers worldwide.  Dan  was also  the technical
   editor for the book {{{cite(Think Like  a Programmer)}}}.  He earned a BS in
   computer  science  from American  Sentinel  University  where he  was  named
   Outstanding  Graduate and  the recipient  of the  Joe @@texinfo:@abbr{B@.}@@
   Wyatt Leadership  Award.  He later earned  an MS in computer  science and is
   currently a  @@texinfo:@abbr{Ph.D}@@ candidate  in computer science  at Nova
   Southeastern University.  He teaches computer science and web development at
   several  universities, including  the UC@@texinfo:@tie{}@@Davis  Division of
   Continuing and Professional Education.  His research interests are currently
   artificial intelligence, programming languages and machine learning.

* Copying
  :PROPERTIES:
  :COPYING:  t
  :END:

This manual is for {{{title}}} Edition {{{EDITION}}}@@texinfo:@*@@
Version {{{VERSION}}} {{{time(%F %R)}}}

Copyright \copy 2018 {{{author}}}

#+BEGIN_QUOTE
Permission is granted to read, learn from, and enjoy this work.
#+END_QUOTE

* Settings :noexport:
#+OPTIONS: H:4

#+TEXINFO_CLASS: info

#+TEXINFO_FILENAME:intro_web_dev.info
#+TEXINFO_PRINTED_TITLE:Intro to Web Development
#+SUBTITLE:From UC Davis --- Edition {{{EDITION}}}@@texinfo:@*@@Version {{{VERSION}}} {{{time(%F %R)}}}

#+TEXINFO_HEADER:
#+TEXINFO_POST_HEADER:

#+TEXINFO_DIR_CATEGORY:Web Development
#+TEXINFO_DIR_TITLE:Introduction to WebDev
#+TEXINFO_DIR_DESC:Introduction to web development from UC Davis

** Macros
#+MACRO: cite @@texinfo:@cite{@@$1@@texinfo:}@@
#+MACRO: var @@texinfo:@var{@@$1@@texinfo:}@@
#+MACRO: kbd (eval (let ((case-fold-search nil) (regexp (regexp-opt '("SPC" "RET" "LFD" "TAB" "BS" "ESC" "DELETE" "SHIFT" "Ctrl" "Meta" "Alt" "Cmd" "Super" "UP" "LEFT" "RIGHT" "DOWN") 'words))) (format "@@texinfo:@kbd{@@%s@@texinfo:}@@" (replace-regexp-in-string regexp "@@texinfo:@key{@@\\&@@texinfo:}@@" $1 t))))
