# -*- mode:org; fill-column:79; -*-

#+TITLE:Introduction to Web Development
#+AUTHOR:WLHarvey4

#+MACRO: EDITION 0.1
#+MACRO: VERSION 0.0.3

#+TEXINFO: @insertcopying

* Course Info


** About this Course
   This course is designed to start you  on a path toward future studies in web
   development  and  design,  no  matter how  little  experience  or  technical
   knowledge you currently have.   The web is a very big place,  and if you are
   the typical  internet user, you  probably visit several websites  every day,
   whether  for  business,  entertainment  or education.   But  have  you  ever
   wondered how  these websites  actually work?   How are  they built?   How do
   browsers, computers, and mobile devices  interact with the web?  What skills
   are necessary to build a website?  With almost 1 billion websites now on the
   internet, the answers  to these questions could be your  first step toward a
   better understanding  of the internet and  developing a new set  of internet
   skills.

   By the  end of  this course  you’ll be  able to  describe the  structure and
   functionality  of the  world  wide web,  create dynamic  web  pages using  a
   combination  of  HTML,  CSS,  and JavaScript,  apply  essential  programming
   language  concepts  when creating  HTML  forms,  select an  appropriate  web
   hosting service, and  publish your webpages for the world  to see.  Finally,
   you’ll be able to develop a working  model for creating your own personal or
   business websites in the future and be  fully prepared to take the next step
   in a more advanced web development or design course or specialization.

   - Level :: Beginner
   - Commitment :: 6 weeks of study, 2-3 hours/week

** About the Instructor
   -  Daniel Randall,  Senior Architect  at Composer Solutions  and Instructor,
     @@texinfo:@abbr{@@U.C. Davis@@texinfo:}@@

   Dan  Randall has  over  25  years’ experience  in  software engineering  and
   information  technology  and currently  works  in  the software  development
   industry focusing  on software  modernization.  He is  the co-author  of the
   {{{cite(Java Web  Services Certification  Exam for Sun  Microsystems)}}} and
   the associated training and practice materials for test takers.  The exam is
   taken by  thousands of  programmers worldwide.  Dan  was also  the technical
   editor for the book {{{cite(Think Like  a Programmer)}}}.  He earned a BS in
   computer  science  from American  Sentinel  University  where he  was  named
   Outstanding  Graduate and  the recipient  of the  Joe @@texinfo:@abbr{B@.}@@
   Wyatt Leadership  Award.  He later earned  an MS in computer  science and is
   currently a  @@texinfo:@abbr{Ph.D}@@ candidate  in computer science  at Nova
   Southeastern University.  He teaches computer science and web development at
   several  universities, including  the UC@@texinfo:@tie{}@@Davis  Division of
   Continuing and Professional Education.  His research interests are currently
   artificial intelligence, programming languages and machine learning.

** Course Overview
   Welcome to the  fundamentals of web development. I commend  you for choosing
   to learn something about the  foundations of web development. Whether you're
   planning on being a  web developer part-time, or just as a  hobby, or even a
   full-time  developer, I  think this  course can  help you  get started.

   My name's  Dan Randall.   I'm a  software developer  and a  computer science
   professor. In  this course we're  going to start  with the basics,  and with
   your attention and practice and a lot of persistence you'll be able to learn
   to create your own websites.  Some of  the things we'll learn in this course
   are  common abbreviations  and terms  used in  web development  and software
   development in  general.  You'll be able  to find and select  your web host,
   register  your  site,   and  discuss  and  work   with  various  client-side
   development techniques, and learn a little bit about server-side development
   and  how  it   works  with  general  web  application   development  on  the
   internet.

   Some of the technologies we'll use  are HTML, CSS, JavaScript, and more. And
   we'll learn more  about those as we  move through the course.  One of things
   you'll learn  is creating a dynamic  HTML site that uses  JavaScript so that
   you'll be able to accept your user's interaction, their input, and make your
   site respond to  their needs.  Learning the fundamentals  of web development
   will help you as you move on to future courses and learn to build larger and
   more complex  sites. Everyone can  use the skills  we teach in  this course.
   Today as we  use the internet more and more,  including mobile phones, these
   skills can benefit everyone,  whether you're treating it as a  hobby or as a
   profession. Thanks for  joining me, I look forward to  working with you, and
   I'll see you in future lessons in the course.

* Website Structure • Hosting

* HTML Basics

* JavaScript

* CSS • Properties • Colors • Fonts

* HTML Forms

* Web Applications

* Copying
  :PROPERTIES:
  :COPYING:  t
  :END:

This manual is for {{{title}}} Edition {{{EDITION}}}@@texinfo:@*@@
Version {{{VERSION}}} {{{time(%F %R)}}}

Copyright \copy 2018 {{{author}}}

#+BEGIN_QUOTE
Permission is granted to read, learn from, and enjoy this work.
#+END_QUOTE

* Settings :noexport:
#+OPTIONS: H:4

#+TEXINFO_CLASS: info

#+TEXINFO_FILENAME:intro_web_dev.info
#+TEXINFO_PRINTED_TITLE:Intro to Web Development
#+SUBTITLE:From UC Davis --- Edition {{{EDITION}}}@@texinfo:@*@@Version {{{VERSION}}} {{{time(%F %R)}}}

#+TEXINFO_HEADER:
#+TEXINFO_POST_HEADER:

#+TEXINFO_DIR_CATEGORY:Web Development
#+TEXINFO_DIR_TITLE:Introduction to WebDev
#+TEXINFO_DIR_DESC:Introduction to web development from UC Davis

** Macros
#+MACRO: cite @@texinfo:@cite{@@$1@@texinfo:}@@
#+MACRO: var @@texinfo:@var{@@$1@@texinfo:}@@
#+MACRO: kbd (eval (let ((case-fold-search nil) (regexp (regexp-opt '("SPC" "RET" "LFD" "TAB" "BS" "ESC" "DELETE" "SHIFT" "Ctrl" "Meta" "Alt" "Cmd" "Super" "UP" "LEFT" "RIGHT" "DOWN") 'words))) (format "@@texinfo:@kbd{@@%s@@texinfo:}@@" (replace-regexp-in-string regexp "@@texinfo:@key{@@\\&@@texinfo:}@@" $1 t))))
